[package]
name = "shadowbreaker"
version = "0.1.0"
authors = ["ChoKyuWon <yyj10137@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pwhash = "0.3"
rayon = "1.5"